In [28]:
import pandas as pd

df = pd.read_csv("Student_performance_data _.csv")

In [3]:
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [18]:
import pandas as pd


df = pd.read_csv("Student_performance_data _.csv")


for col in df.columns:
    if df[col].nunique() < 5:  
        df[col] = df[col].astype('object')
    else:
        df[col] = pd.to_numeric(df[col], errors='coerce')  


print(df.dtypes)

StudentID              int64
Age                   object
Gender                object
Ethnicity             object
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring              object
ParentalSupport        int64
Extracurricular       object
Sports                object
Music                 object
Volunteering          object
GPA                  float64
GradeClass           float64
dtype: object

# For all feature types, there are no missing values

In [2]:
import pandas as pd

df = pd.read_csv("Student_performance_data _.csv")

df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

# By this result, it looks like Music, Volunteering, and ParentalEducation seems to have outliers.

In [36]:
import pandas as pd

# Load the dataset
df = pd.read_csv("Student_performance_data _.csv")  

# Function to detect outliers using IQR
def detect_outliers_iqr(data):
    outlier_summary = {}

    # Automatically identify numerical columns
    numerical_columns = data.select_dtypes(include=['int64', 'float64']).columns

    for column in numerical_columns:
        Q1 = data[column].quantile(0.25)
        Q3 = data[column].quantile(0.75)
        IQR = Q3 - Q1  # Interquartile range

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        num_outliers = len(data[(data[column] < lower_bound) | (data[column] > upper_bound)])

        outlier_summary[column] = {
            "Lower Bound": lower_bound,
            "Upper Bound": upper_bound,
            "Number of Outliers": num_outliers
        }

    return outlier_summary

# Detect outliers for all numerical features
outliers = detect_outliers_iqr(df)

# Print outlier summary
for feature, stats in outliers.items():
    print(f"\n{feature}")
    print(f"Lower Bound: {stats['Lower Bound']}")
    print(f"Upper Bound: {stats['Upper Bound']}")
    print(f"Number of Outliers: {stats['Number of Outliers']}")

StudentID
Lower Bound: -194.5
Upper Bound: 4587.5
Number of Outliers: 0

Age
Lower Bound: 12.0
Upper Bound: 20.0
Number of Outliers: 0

Gender
Lower Bound: -1.5
Upper Bound: 2.5
Number of Outliers: 0

Ethnicity
Lower Bound: -3.0
Upper Bound: 5.0
Number of Outliers: 0

ParentalEducation
Lower Bound: -0.5
Upper Bound: 3.5
Number of Outliers: 120

StudyTimeWeekly
Lower Bound: -9.004916417421299
Upper Bound: 28.456405126475232
Number of Outliers: 0

Absences
Lower Bound: -15.5
Upper Bound: 44.5
Number of Outliers: 0

Tutoring
Lower Bound: -1.5
Upper Bound: 2.5
Number of Outliers: 0

ParentalSupport
Lower Bound: -2.0
Upper Bound: 6.0
Number of Outliers: 0

Extracurricular
Lower Bound: -1.5
Upper Bound: 2.5
Number of Outliers: 0

Sports
Lower Bound: -1.5
Upper Bound: 2.5
Number of Outliers: 0

Music
Lower Bound: 0.0
Upper Bound: 0.0
Number of Outliers: 471

Volunteering
Lower Bound: 0.0
Upper Bound: 0.0
Number of Outliers: 376

GPA
Lower Bound: -0.9963156384671206
Upper Bound: 4.793335255801528
Number of Outliers: 0

GradeClass
Lower Bound: -1.0
Upper Bound: 7.0
Number of Outliers: 0

In [6]:
import numpy as np
import pandas as pd

df = pd.read_csv("Student_performance_data _.csv")

df["ParentalEducation"] = np.log1p(df["ParentalEducation"])  # Log transformation
df["Music"] = np.sqrt(df["Music"])  # Square root transformation
df["Volunteering"] = np.sqrt(df["Volunteering"])

In [ ]:
histogram tour target, make comments to yourself if each class is or bad, how to scale, visualize to see if the scaling works, 3 dfferent

# Class Imbalance

There is an inbalance because I used df[target_column].value_counts() to count how many occurrences exist for each unique grade classification.

Thatâ€™s why the result shows how many students fall into each category, where grade 4.0 appears most frequently (1,211 students), followed by 3.0, 2.0, 1.0, and finally 0.0


Then for the Class Proportion, I divided the class distribution count by the total number of students using (class_distribution / len(df)) * 100 to get the percentage representation.

Grade 4.0 makes up about 50.63% of the dataset, while 0.0 accounts for only 4.47%, revealing an imbalance.

In [21]:
import pandas as pd

# Load the dataset
df = pd.read_csv("Student_performance_data _.csv")  # Replace with your file path

# Define the target column for classification
target_column = "GradeClass"  # Replace with the actual column name for classification

# Check class distribution
class_distribution = df[target_column].value_counts()

# Print class distribution and proportion
print("Class Distribution:")
print(class_distribution)

print("\nClass Proportion:")
print(class_distribution / len(df) * 100)

Class Distribution:
GradeClass
4.0    1211
3.0     414
2.0     391
1.0     269
0.0     107
Name: count, dtype: int64

Class Proportion:
GradeClass
4.0    50.627090
3.0    17.307692
2.0    16.346154
1.0    11.245819
0.0     4.473244
Name: count, dtype: float64

For regression the range is GPA, where the model is predicting a continuous value (0.0 to 4.0). This is to understand the boundaries of the GPA column. This is to determine minimum and maximum to gain insight into the target's numerical range.

Since this regression model predicts continuous values, knowing the range of the target variable (GPA) is cricial to understanding what will produce. So, we know the GPA values lie between 0.0 to 4.0, reflecting academic performance.

In [26]:
regression_target = "GPA"

min_value = df[regression_target].min()
max_value = df[regression_target].max()

print(f"Regression Target Range: {min_value} to {max_value}")

Regression Target Range: 0.0 to 4.0

In [ ]:
FIND constant, duplicate variables, no answers, drop these variables from the data. 

write a range function that changes target variable to 0 and 1 0 representing a failing GPA and 1 representing a Passing GPA

In [8]:
import pandas as pd

# Example dataset
data = {
    "Gender": ["Male", "Female", "Male", "Female"],
    "Ethnicity": ["Asian", "White", "Hispanic", "Black"],
    "ParentalEducation": ["HighSchool", "College", "HighSchool", "Graduate"],
    "Extracurricular": ["Sports", "Music", "Volunteering", "Sports"],
    "Tutoring": ["Yes", "No", "Yes", "No"],
    "ParentalSupport": ["Yes", "Yes", "No", "Yes"],
    "Sports": ["Football", "Basketball", "None", "Basketball"],
    "Music": ["None", "Guitar", "Piano", "Guitar"],
    "Volunteering": ["None", "Community", "None", "Animal"],
}

df = pd.DataFrame(data)

# One-hot encode categorical features
categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Extracurricular', 
                        'Tutoring', 'ParentalSupport', 'Sports', 'Music', 'Volunteering']
df_encoded = pd.get_dummies(df, columns=categorical_features, drop_first=True)

# Display the resulting dataset
print("Encoded Dataset:")
print(df_encoded)

Encoded Dataset:
   Gender_Male  Ethnicity_Black  Ethnicity_Hispanic  Ethnicity_White  \
0         True            False               False            False
1        False            False               False             True
2         True            False                True            False
3        False             True               False            False

   ParentalEducation_Graduate  ParentalEducation_HighSchool  \
0                       False                          True
1                       False                         False
2                       False                          True
3                        True                         False

   Extracurricular_Sports  Extracurricular_Volunteering  Tutoring_Yes  \
0                    True                         False          True
1                   False                         False         False
2                   False                          True          True
3                    True                         False         False

   ParentalSupport_Yes  Sports_Football  Sports_None  Music_None  Music_Piano  \
0                 True             True        False        True        False
1                 True            False        False       False        False
2                False            False         True       False         True
3                 True            False        False       False        False

   Volunteering_Community  Volunteering_None
0                   False               True
1                    True              False
2                   False               True
3                   False              False